server:
  port: 8080
management:
  endpoint:
    web:
      exposure:
        include: "*"
  info:
    env:
      enable: true

spring:
  cloud:
    gateway:
      enabled: true
      routes:
        - id: query_route
          uri: https://www.baidu.com
          predicates:
            - Query=green
