server:
  port: 8040
management:
  endpoint:
    web:
      exposure:
        include: "*"
  info:
    env:
      enable: true

spring:
  cloud:
    gateway:
      enabled: true
      routes:
        - id: hello
          uri: http://localhost:8080/
          predicates:
            - Path=/hellomvc/**
          filters:
            - StripPrefix=1
        - id: login
          uri: https://www.baidu.com
          predicates:
            - Path=/login
