server:
  port: 8081
  compression:
    enabled: true
    min-response-size: 800
  tomcat:
    max-connections: 2000
    max-threads: 1024
    min-spare-threads: 64
    accept-count: 2000
spring:
  application:
    name: hello-web-mvc