server:
  port: 8081
  compression:
    enabled: true
    min-response-size: 800
  tomcat:
    max-connections: 2000
    max-threads: 1024
    min-spare-threads: 64
    accept-count: 2000
spring:
  application:
    name: hello-web-mvc
###################################################
hystrix:
  threadpool:
    default:
      coreSize: 1000 #缺省为10
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
          strategy: THREAD

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  MaxTotalHttpConnections: 5000
  MaxConnectionsPerHost: 5000
########################################################
feign:
  httpclient:
    enabled: true
    max-connections: 5000
    max-connections-per-route: 1000