spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8083
  tomcat:
    max-connections: 2000
    max-threads: 1024
    min-spare-threads: 64
    accept-count: 2000

feign:
  httpclient:
    enabled: true
    max-connections: 5000
    max-connections-per-route: 1000
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 100
    response:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-response-size: 100
###################################################
logging:
  level:
    root: info
    com.yicj.study.feign: debug